language: java

addons:
  sonarcloud:
    organization: "napstr-github"
    token:
      secure: "lWokv1JtxppNnKuf9U7UGBAMEAN9pK0hO+DNMujMHoU5B18+L/aTi5jBycTWji8dlAVkEMN87uDl0xooLc//wT1b42kI3R0j0oMJuUGUf/pTpqYUomEHs3rfUPCIKqqtUPln1qbMghJ0c6LOQzYTPOELKH66q1Hm+byvDSuFcljPKqqgQZRBtIN4u2ekJRIXqBoeDqoBf9MyxMWtNcDivmLVaLFIxuvPxaK+7aiKlul505MjfVb2uLy79fAfejfoz8VVX5lqF4pJraG8lhrFytMuDEa4ib4ICPXhDP1PapE7RPOLHdQq4HTrV//Xa7dTdTJh0g71I2NEiPTQEcW107LeEY2CVO3MVolrfulzl3vL79up5m5HI6TQCSfKM4LzdZ2mBIN87lg+3PO0v4FnXpjHWIlcz62nKfsjNHm1FeWIbhsqfHULh8Ugv688K0PmCnX0/2EYTVtNFo5ULSPNSFgPN3IB38HkjLAQp+uDMI4OEgInwDf/dutjd6AdjSb0e77ArQ28p5dHJCVSMAqOB/9s0SaLgaw4egy9mZpIgUIvlPca1Im85A1SHs6gmQk72TOnt2L/1NsCEyHIoU9jdU+nRghsaOUdHBSqvS7ZUXDIoRfrfZy2/PCCC3lIfT6vyhKdYtzsou4z8eebHXTQqk10mWHZMeowxfa5JcuwazE="

env:
  global:
    - BUILD_NUMBER: "$TRAVIS_BUILD_NUMBER"

cache:
  directories:
    - "$HOME/.m2"
    - "$HOME/.gradle/wrapper"
    - "$HOME/.gradle/caches"
    - "$HOME/.sonar/cache"

stages:
  - build & test
  - sonar

jobs:
  fast_finish: true
  allow_failures:
    - jdk: openjdk-ea
  include:
    - stage: build & test
      jdk: openjdk8
      script:
        - "java -Xmx32m -version"
        - "./gradlew build --info"

    - stage: build & test
      jdk: openjdk11
      script:
        - "java -Xmx32m -version"
        - "./gradlew build --info"

    - stage: build & test
      jdk: openjdk12
      script:
        - "java -Xmx32m -version"
        - "./gradlew build --info"

    - stage: build & test
      jdk: openjdk-ea
      script:
        - "java -Xmx32m -version"
        - "./gradlew build --info"


    - stage: sonar
      jdk: openjdk11
      before_script:
        #for full sonar cloud blame information
        - "git fetch --unshallow"
      script:
        - "./gradlew sonarqube"
